# Tensor Initialization

Get access to torch library

In [1]:
import torch

Display version of torch library

In [2]:
torch.__version__

'1.10.0'

Set torch device on GPU if GPU is available

In [3]:
device = "cuda" if torch.cuda.is_available() else "cpu"

Create a 2D tensor with float type elements and allocate tensor on chosen device A tensor can be created with requires_grad=True so that torch.autograd records operations on them for automatic differentiation

In [4]:
my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32, device=device, requires_grad=True)

In [5]:
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)

Display tensor attribute

In [6]:
my_tensor.dtype

torch.float32

In [7]:
my_tensor.device

device(type='cuda', index=0)

In [8]:
my_tensor.requires_grad

True

## Other common initialization methods

Create empty tensor with specific size

In [9]:
x = torch.empty(size=(3, 3))
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

Create zero tensor with specific size

In [10]:
x = torch.zeros(size=(3, 3))
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

Create a random tensor with a specific size that elements are between 0 and 1

In [11]:
x = torch.rand(size=(3, 3))
x

tensor([[0.0506, 0.9060, 0.4222],
        [0.0072, 0.2473, 0.0295],
        [0.5915, 0.5130, 0.1004]])

Create a tensor with a specific size that elements are 1

In [12]:
x = torch.ones(size=(3, 3))
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

Create a identity tensor with a specific size

In [13]:
x = torch.eye(n=5)
x

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

Create a 1D tensor with values from the interval [start, end) taken with common difference step beginning from start.

In [14]:
x = torch.arange(start=0, end=5, step=1)
x

tensor([0, 1, 2, 3, 4])

Creates a 1D tensor of size steps whose values are evenly spaced from start to end, inclusive.

In [15]:
x = torch.linspace(start=0.1, end=1, steps=10)
x

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

Fills tensor with elements samples from the normal distribution parameterized by mean and std.

In [16]:
x = torch.empty(size=(1, 5)).normal_(mean=0, std=1)
x

tensor([[ 0.0183, -0.9207,  1.0316,  0.1307, -1.6224]])

Fills tensor with numbers sampled from the continuous uniform distribution:

In [17]:
x = torch.empty(size=(1, 5)).uniform_(0, 1)
x

tensor([[0.1254, 0.1371, 0.9259, 0.3138, 0.6046]])

Create the diagonal of tensor.

In [18]:
x = torch.diag(torch.ones(3))
x

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

## How to initialize and convert tensors to others types

In [19]:
tensor = torch.arange(4)
tensor

tensor([0, 1, 2, 3])

Convert to boolean type

In [20]:
tensor.bool()

tensor([False,  True,  True,  True])

Convert to int16 type

In [21]:
tensor.short()

tensor([0, 1, 2, 3], dtype=torch.int16)

Convert to int64 type

In [22]:
tensor.long()

tensor([0, 1, 2, 3])

Convert to float16 type

In [23]:
tensor.half()

tensor([0., 1., 2., 3.], dtype=torch.float16)

Convert to float32 type

In [24]:
tensor.float()

tensor([0., 1., 2., 3.])

Convert to float64 type

In [25]:
tensor.double()

tensor([0., 1., 2., 3.], dtype=torch.float64)

## Array to Tensor conversion and vice-versa

In [26]:
import numpy as np
np_array = np.zeros((5, 5))
np_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
tensor = torch.from_numpy(np_array)
tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)

In [28]:
np_array_back = tensor.numpy()
np_array_back

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])