# Tensor Math & Comparison Operations

In [1]:
import torch

In [2]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([9, 8, 7])

### Addition

In [3]:
z1 = torch.empty(3)

In [4]:
torch.add(x, y, out=z1)
z1

tensor([10., 10., 10.])

In [5]:
z2 = torch.add(x, y)
z2

tensor([10, 10, 10])

In [6]:
z = x + y
z

tensor([10, 10, 10])

### Subtraction

In [7]:
z = x - y
z

tensor([-8, -6, -4])

### Division

In [8]:
z1 = torch.true_divide(x, 2)
z1

tensor([0.5000, 1.0000, 1.5000])

In [9]:
z2 = torch.true_divide(x, y)
z2

tensor([0.1111, 0.2500, 0.4286])

### Inplace operations

In [10]:
t = torch.zeros(3)
t

tensor([0., 0., 0.])

In [11]:
t.add_(x)

tensor([1., 2., 3.])

In [12]:
t += x
t

tensor([2., 4., 6.])

### Exponentiation

In [13]:
z = x.pow(2)
z

tensor([1, 4, 9])

In [14]:
z = x ** 2
z

tensor([1, 4, 9])

### Simple comparison

In [15]:
z = x > 0
z

tensor([True, True, True])

In [16]:
z = x < 0
z

tensor([False, False, False])

### Matrix multiplication

In [17]:
x1 = torch.rand((2, 5))
x2 = torch.rand((5, 3))

In [18]:
x3 = torch.mm(x1, x2)
x3

tensor([[1.1204, 1.9174, 1.6920],
        [0.7034, 1.4237, 1.1133]])

In [19]:
x3 = x1.mm(x2)
x3

tensor([[1.1204, 1.9174, 1.6920],
        [0.7034, 1.4237, 1.1133]])

### Matrix exponentiation

In [20]:
matrix_exp = torch.rand(5, 5)
matrix_exp

tensor([[0.4189, 0.2113, 0.2967, 0.1961, 0.1030],
        [0.4349, 0.1352, 0.8106, 0.0991, 0.5568],
        [0.9948, 0.4286, 0.2412, 0.2642, 0.2144],
        [0.9281, 0.4055, 0.1148, 0.9662, 0.8563],
        [0.2479, 0.5532, 0.7898, 0.7716, 0.6765]])

In [21]:
matrix_exp.matrix_power(3)

tensor([[1.4893, 0.8543, 1.0673, 1.1048, 1.0905],
        [2.7317, 1.5162, 1.9387, 1.9571, 1.9989],
        [2.4934, 1.4235, 1.7265, 1.8082, 1.7785],
        [4.8162, 2.8621, 3.4139, 3.9776, 3.9044],
        [4.5416, 2.6913, 3.3160, 3.6391, 3.5850]])

### Element wise multiplication

In [22]:
z = x * y
z

tensor([ 9, 16, 21])

In [23]:
z = x ** y
z

tensor([   1,  256, 2187])

### Dot product

In [24]:
z = torch.dot(x, y)
z

tensor(46)

### Batch matrix multiplication

In [25]:
batch = 32
n = 10
m = 20
p = 30

tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))

out_bmm = torch.bmm(tensor1, tensor2)
out_bmm.shape

torch.Size([32, 10, 30])

### Brodcasting

In [26]:
x1 = torch.rand((5, 5))
x2 = torch.rand((1, 5))

z = x1 - x2
z

tensor([[ 0.6574,  0.8016,  0.7053,  0.9835,  0.5487],
        [ 0.1515,  0.3854,  0.0227,  0.8596,  0.0777],
        [ 0.2258,  0.5961,  0.6158,  0.8444,  0.2568],
        [ 0.4973,  0.5823, -0.2144,  0.2279,  0.0891],
        [ 0.5146,  0.5465,  0.1342,  0.5796, -0.0220]])

In [27]:
z = x1 ** x2
z

tensor([[0.9770, 0.9900, 0.9827, 0.9999, 0.9467],
        [0.7948, 0.9239, 0.7332, 0.9989, 0.7533],
        [0.8295, 0.9617, 0.9611, 0.9987, 0.8419],
        [0.9300, 0.9596, 0.2861, 0.9886, 0.7598],
        [0.9355, 0.9538, 0.7967, 0.9958, 0.6877]])

### Other useful tensor operations

In [28]:
sum_x = torch.sum(x, dim=0)
sum_x

tensor(6)

In [29]:
values, indices = torch.max(x, dim=0)
values, indices

(tensor(3), tensor(2))

In [30]:
values, indices = torch.min(x, dim=0)
values, indices

(tensor(1), tensor(0))

In [31]:
abs_x = torch.abs(x)
abs_x

tensor([1, 2, 3])

In [32]:
z = torch.argmax(x, dim=0)
z

tensor(2)

In [33]:
z = torch.argmin(x, dim=0)
z

tensor(0)

In [34]:
mean_x = torch.mean(x.float(), dim=0)
mean_x

tensor(2.)

In [35]:
z = torch.eq(x, y)
z

tensor([False, False, False])

In [36]:
sorted_y, indices = torch.sort(y, dim=0, descending=False)
sorted_y, indices

(tensor([7, 8, 9]), tensor([2, 1, 0]))

In [37]:
z = torch.clamp(x, min=0, max=10)
z

tensor([1, 2, 3])

In [38]:
x = torch.tensor([1, 0, 1, 1, 1], dtype=torch.bool)
z = torch.any(x)
z

tensor(True)

In [39]:
z = torch.all(x)
z

tensor(False)