# Tensor Reshaping

In [1]:
import torch

In [2]:
x = torch.arange(9)

In [4]:
x_3x3 = x.view(3, 3)
x_3x3

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [5]:
x_3x3 = x.reshape(3, 3)
x_3x3

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [6]:
y = x_3x3.t()
y

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])

In [8]:
y.view(9)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [12]:
y.contiguous().view(9)

tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])

In [13]:
x1 = torch.rand((2, 5))
x2 = torch.rand((2, 5))
y = torch.cat((x1, x2), dim=0)
y.shape

torch.Size([4, 5])

In [14]:
y = torch.cat((x1, x2), dim=1)
y.shape

torch.Size([2, 10])

In [15]:
z = x1.view(-1)
z.shape

torch.Size([10])

In [16]:
batch = 64
x = torch.rand((batch, 2, 5))
z = x.view(batch, -1)
z.shape

torch.Size([64, 10])

In [17]:
z = x.permute(0, 2, 1)
z.shape

torch.Size([64, 5, 2])

In [18]:
x = torch.arange(10)
z = x.unsqueeze(dim=0)
z.shape

torch.Size([1, 10])

In [19]:
z = x.unsqueeze(dim=1)
z.shape

torch.Size([10, 1])

In [20]:
x = torch.arange(10).unsqueeze(dim=0).unsqueeze(dim=1)
x.shape

torch.Size([1, 1, 10])

In [21]:
z = x.squeeze(1)
z.shape

torch.Size([1, 10])